# This is a workflow

name: CREATE MABL FEATURE BRANCH

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    types: [labeled]
    branches: [mimir-367-dronecli]
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "create_mabl_branch"
  create_mabl_branch:
    if: ${{ github.event.label.name == 'run mabl test' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: install mabl
      run: npm install -g @mablhq/mabl-cli
    - name: Branch name
      run: echo running on branch ${GITHUB_HEAD_REF##*/} or ${GITHUB_REF##*/} with label ${{ github.event.label.name }}
    - name: create mabl branch
      env:
        MABL_API_KEY: ${{ secrets.MABLAPIKEY }}
      run: |
        mabl auth activate-key $MABL_API_KEY
        mabl branches create ${GITHUB_HEAD_REF##*/}


