name: Test

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: chrislennon/action-drone@v1
        with:
          version: '0.8.1'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - run: drone info
        env:
          #DRONE_SERVER: ${{ secrets.DRONE_SERVER }}
          DRONE_SERVER: ssb-drone.enonic.cloud
          #DRONE_TOKEN: ${{ secrets.DRONE_TOKEN }}
          DRONE_TOKEN: nUXyf8glrBodbKc2Y5QAThBEbFwPyarL
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
