# This is a workflow that is manually triggered

name: MIMIR MABL

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  mabl_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Git checkout
      uses: actions/checkout@v2
    - name: Branch name
      run: echo running on branch ${GITHUB_HEAD_REF##*/} or ${GITHUB_REF##*/}
    - name: commit hash
      run: echo running $(echo $GITHUB_SHA | cut -c1-8) and ${GITHUB_SHA}
    - name: runs mabl tests 
      id: mabl-test-deployment
      env:
        MABL_API_KEY: ${{ secrets.MABLAPIKEY }}
        MABL_APP_ID: ${{ secrets.MABLAPPID }}
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install -g @mablhq/mabl-cli
        mabl deployments create --api-key $MABL_API_KEY --application-id $MABL_APP_ID --mabl-branch ${GITHUB_HEAD_REF##*/} --labels MIMIR --revision ${GITHUB_SHA} --auto-branch true --await-completion

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
       # run: |
        #  echo Add other actions to build,
         # echo test, and deploy your project.

