# This is a workflow that is manually triggered

name: MERGE MABL FEATURE BRANCH

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [mimir-285-commit-id]
  workflow_dispatch:
   # Inputs the workflow accepts.
    branch:
        # Friendly description to be shown in the UI instead of 'branch'
        description: 'Branch'
        # Default value if no value is explicitly provided
        default: 'mimir-'
        # Input has to be provided for the workflow to run
        required: false
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "merge_mabl_branch"
  merge_mabl_branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: install mabl
      run: npm install -g @mablhq/mabl-cli
    - name: Branch name
      run: echo running on branch ${GITHUB_HEAD_REF##*/} or ${GITHUB_REF##*/} or ${{ github.event.inputs.branch }}
    - name: merge mabl branch
      env:
        MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
      run: |
        mabl auth activate-key $MABL_API_KEY
        mabl branches merge --from ${GITHUB_HEAD_REF##*/}
